name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the distribution (e.g., temurin, zulu)
          cache: 'maven'  # Optional: To cache Maven dependencies

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t sachintharuka/aws-assignment:$GITHUB_SHA -t sachintharuka/aws-assignment:latest .
          docker push sachintharuka/aws-assignment:$GITHUB_SHA
          docker push sachintharuka/aws-assignment:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes (Development)
        run: |
          kubectl apply -f ./aws-assignment/deployment.yaml
