name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the distribution (e.g., temurin, zulu)
          cache: 'maven'  # Optional: To cache Maven dependencies

      - name: Build with Maven
        run: mvn clean install

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t aws-assignment/aws-assignment:$GITHUB_SHA .
            docker build -t sachintharuka/aws-assignment:latest ./aws-assignment
            docker push sachintharuka/aws-assignment:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes (Development)
        if: github.ref == 'refs/heads/dev'
        run: |
          kubectl apply -f k8s/aws-assignment-dev.yaml
      - name: Deploy to Kubernetes (Test)
        if: github.ref == 'refs/heads/test'
        run: |
          kubectl apply -f k8s/aws-assignment-test.yaml
      - name: Deploy to Kubernetes (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl apply -f k8s/aws-assignment-prod.yaml
